AWSTemplateFormatVersion: 2010-09-09
Description: Foundation Services
Transform: AWS::Serverless-2016-10-31
Resources:
  GraphqlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./graphql-go/graphql/main
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /query
            Method: post

  ServerlessLumenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-serverless-lumen
      Description: PHP Webserver
      CodeUri: serverless-lumen
      Runtime: provided
      Handler: index.php
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:887080169480:layer:php73:2
      Events:
        api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  # define next microservice here